CREATE DATABASE users;

CREATE TABLE clients(
id BIGSERIAL NOT NULL PRIMARY KEY,
username VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
password TEXT NOT NULL
);

CREATE TABLE products(
id BIGSERIAL NOT NULL PRIMARY KEY,
product_name VARCHAR(150) NOT NULL,
price NUMERIC(19,2),
username VARCHAR(100) NOT NULL REFERENCES clients(username)
);


